# Generated by Django 4.1.5 on 2023-01-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Real_name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('Type_counte', models.BooleanField(db_column='typeUtil', default=False, max_length=26)),
            ],
            options={
                'db_table': 'Utilisateur',
                'managed': True,
            },
        ),
    ]
