# Generated by Django 4.1.5 on 2023-01-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur2',
            name='Type_counte',
            field=models.BooleanField(default=False, max_length=26),
        ),
    ]
