# Generated by Django 4.1.5 on 2023-01-14 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Acount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_Pharmacie', models.CharField(db_column='Nom Pharmacie', max_length=255)),
                ('adresse', models.CharField(db_column='Adresse', max_length=255)),
                ('Locality', models.CharField(db_column='Locality', max_length=255)),
                ('City_District_Town', models.CharField(db_column='City_District_Town', max_length=255)),
                ('PinCode', models.CharField(db_column='PinCode', max_length=255)),
                ('state', models.CharField(db_column='state', max_length=255)),
                ('tel', models.CharField(db_column='Tel', max_length=255)),
                ('position_lat', models.DecimalField(decimal_places=6, max_digits=6)),
                ('position_lng', models.DecimalField(decimal_places=6, max_digits=6)),
                ('sidegarde', models.BooleanField(db_column='sidegarde', default=False, max_length=26)),
                ('idutil', models.ForeignKey(db_column='idutil', on_delete=django.db.models.deletion.DO_NOTHING, to='Acount.utilisateur2')),
            ],
            options={
                'db_table': 'Pharmacie',
            },
        ),
    ]
